### ISSUE TITLE
Version 2.0 Deleted All Of My Plugins

### ISSUE THREAD

**Issue by gdwaynewarner** [fourshade/spectra_lexer#1]
While using Plover 4.0.0.dev8+66.g685bd33 on my 2008 iMac, I updated Spectra Lexer to version 2.0, and restarted Plover as usual.

When Plover restarted, my Plugins icon was gone from the main window, as well as from the Tools menu.

I quit Plover, then sent Ted my plover.cfg and plover.log files, but he reported there was nothing unusual in them.

I then deleted the aforementioned files along with Plugins folder, restarted Plover, and the Plugins menu item appeared ... so I was then able to reinstall all of my plugins, but left out Spectra Lexer.
![Screen Shot 2019-03-11 at 2 03 22 AM](https://user-images.githubusercontent.com/17680111/54197163-73c05d00-4480-11e9-8e7b-1f2f7f2cdd31.png)
![Screen Shot 2019-03-11 at 2 13 06 AM](https://user-images.githubusercontent.com/17680111/54197164-7458f380-4480-11e9-9d76-4899606d7cb8.png)

Ted congratulated me on finding a new bug (thanks, Ted!).

**Comment by fourshade** [comment]
Oh wow, I had no idea anyone knew this repo existed. Sorry for being so late.

I've had issues with the plugins manager before but came up empty trying to find something specific to Spectra. As far as Plover is concerned, the plugins manager _is itself a plugin_, so the fact that it's gone while your other plugins remain is even more curious. I suspect it might have something to do with the fact that it's built into Plover while the others are externally downloaded.

Spectra tries to bother Plover as little as possible, really. It hooks in with a GUI tool entry point just like other stuff on the toolbar and connects to the "dictionaries_loaded" and "translated" signals. For the first one it copies the Plover dictionaries for its own use, for the second, it looks inside the engine to see if the user stroked anything worth making a diagram out of. As far as I know it doesn't modify _anything_ on Plover's side; 

Anyway, version 6 is coming out now and I've hacked the framework up so much there's barely anything left from months 4 ago. Hopefully whatever new bugs come into existence will stomp out the old for a sense of balance.

**Comment by fourshade** [comment]
As far as I know there's no more problem now. The plugins manager uses the QtWebEngine component, which throws a fit if other components run Qt code before it does. Plover seems to load plugins alphabetically, and my entry point "lexer_plugin" is before "plugins_manager", so the problem occurs if certain Qt objects are created at the module or class level (i.e. at import time). Moving these into instance methods seemed to clear things up.
