### ISSUE TITLE
SPW is not STP

### ISSUE THREAD

**Issue by transitracer** [fourshade/spectra_lexer#2]
![spw](https://user-images.githubusercontent.com/36526063/65362503-a5577500-dbd5-11e9-9fab-bd7fae436bc2.png)

This bug really confused me for a minute, because I've gotten in the habit of looking at the images more than the actual notation

**Comment by fourshade** [comment]
The entire board diagram generator has been redone, and that mistake is long gone. Just need to find a good-looking way to draw it over the SPW keys now without making it look like T or K is involved.
