### ISSUE TITLE
Is it multilingual?

### ISSUE THREAD

**Issue by flamenco108** [fourshade/spectra_lexer#8]
Hello.
I just would like to ask if spectra works with other dictionaries and key-layouts than Plover?
I mean, I create dictionary and key-layout for Polish, load it to Plover and start spectra plugin. Would it work?

**Comment by fourshade** [comment]
The layout and rule set aren't hardcoded, so in theory there's nothing preventing it from working with other languages, but the only one it has by default is English. There are three JSON-based data files that define what the key layout is, what the rules are, and how the board diagrams are drawn. Changing the [key layout](https://github.com/fourshade/spectra_lexer/blob/master/spectra_lexer/assets/key_layout.cson) is probably easy enough, but [codifying the rules](https://github.com/fourshade/spectra_lexer/blob/master/spectra_lexer/assets/rules.cson) that govern another steno theory would take significant effort. Without new rules it won't be able to make heads or tails of input from another language.
